"""Change type to enum

Revision ID: 93d0708acd30
Revises: aac4d3ef4e38
Create Date: 2025-05-24 15:14:43.443222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93d0708acd30'
down_revision: Union[str, None] = 'aac4d3ef4e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('synthetic_data_runs', 'status',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', name='runstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('synthetic_data_runs', 'status',
               existing_type=sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', name='runstatus'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
